### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by lengushuru** [shafiuyushawu/Awesome-Books#4]
**Great work implementing all the project requirement, please consider making the following changes**

1. Address in contact section: the `<ul>` should be enclosed in an <address> tag in HTML file.
2. Modules not linked properly in JavaScript file
3.  Navigation bar should be fixed to function properly.

**Comment by shafiuyushawu** [comment]
Dear Team,

All changes resolved
Appreciate your feedback
